export const INGREDIENTS = Object.freeze([
  "Bacon",
  "Basil",
  "Black Olives",
  "Canadian Bacon",
  "Chicken",
  "Crushed Garlic",
  "Feta",
  "Fresh Mozzarella",
  "Goat Cheese",
  "Green Onions",
  "Green Peppers",
  "Jalapeños",
  "Meatballs",
  "Mushrooms",
  "Pepperoni",
  "Pepperoncinis",
  "Pineapple",
  "Red Onions",
  "Ricotta",
  "Roasted Garlic",
  "Salami",
  "Sausage",
  "Spinach",
  "Tomatoes",
  "White Onions",
]);
